A/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
	path('register/', views.UserRegister.as_view(), name='register'),
	path('login/', views.UserLogin.as_view(), name='login'),
	path('logout/', views.UserLogout.as_view(), name='logout'),
]

core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
	path('', views.Home.as_view(), name='home'),
	path('<int:id>/<slug:slug>/', views.QuestionDetail.as_view(), name='detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Question(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions')
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	closed = models.BooleanField(default=False)

	def __str__(self):
		return f'{self.user} - {self.title[:20]}'

	def get_absolute_url(self):
		return reverse('core:detail', args=[self.id, self.slug])


class Answer(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='answers')
	question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.question.title[:20]}'

accounts/forms.py
from django import forms


class UserRegistrationForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))


class UserLoginFrom(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

core/forms.py
from django import forms


class SearchForm(forms.Form):
	search = forms.CharField()

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegistrationForm, UserLoginFrom
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


class UserRegister(View):
	form_class = UserRegistrationForm
	template_name = 'accounts/register.html'

	def get(self, request):
		form = self.form_class
		return render(request, self.template_name, {'form':form})

	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = User.objects.create_user(cd['username'], cd['email'], cd['password'])
			user.save()
			messages.success(request, 'you registered successfully', 'info')
			return redirect('core:home')
		return render(request, self.template_name, {'form':form})


class UserLogin(View):
	form_class = UserLoginFrom
	template_name = 'accounts/login.html'

	def get(self, request):
		form = self.form_class
		return render(request, self.template_name, {'form':form})

	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(request, username=cd['username'], password=cd['password'])
			if user is not None:
				login(request, user)
				messages.success(request, 'you logged in successfully', 'info')
				return redirect('core:home')
			messages.error(request, 'username or password is wrong', 'warning')
		return render(request, self.template_name, {'form':form})


class UserLogout(View):
	def get(self, request):
		logout(request)
		messages.success(request, 'you logged out successfully', 'info')
		return redirect('core:home')

core/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Question
from .forms import SearchForm
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models.functions import Greatest


class Home(View):
	form_class = SearchForm

	def get(self, request):
		form = self.form_class
		questions = Question.objects.all()
		if 'search' in request.GET:
			form = self.form_class(request.GET)
			if form.is_valid():
				query = form.cleaned_data['search']
				questions = questions.annotate(similarity = Greatest(TrigramSimilarity('title', query), TrigramSimilarity('body', query))).filter(similarity__gt=0).order_by('-similarity')
		return render(request, 'core/home.html', {'questions':questions, 'form':form})


class QuestionDetail(View):
	def get(self, request, id, slug):
		question = get_object_or_404(Question, id=id, slug=slug)
		return render(request, 'core/detail.html', {'question':question})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

core/templates/core/detail.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ question.title }}</h3>
    <smal>{{ question.created }} - {{ question.user }}</smal>
    <p>{{ question.body }}</p> <hr>

    {% for answer in question.answers.all %}
        <p>{{ answer.body }} - {{ answer.user }}</p>
    {% endfor %}

{% endblock %}

core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
    <h3>Home</h3>

    <form action="">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>

    <div class="card">
        {% for question in questions %}
            <a href="{{ question.get_absolute_url }}" class="card-body">{{ question.title }}</a>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

    {% include 'inc/navbar.html' %}
    <div class="jumbotron">
    {% include 'inc/messages.html' %}
    {% block content %} {% endblock %}
    </div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'core:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
        <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">Login</a>
        <a class="nav-item nav-link active" href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
    </div>
</nav>